better log message
jeertmans/rpdf pull request #86
Opened 2024-10-12 14:08 UTC by Brijeshthummar02

issue #78

2024-10-12 18:53 UTC, jeertmans requested changes
Small comments but looks great otherwise :-)

2024-10-12 18:53 UTC, jeertmans commented on src/cli/annotations.rs
> +>>>>>>> 85f3c4e8c9845f468b57c250633363d773b01d2b
Hi @Brijeshthummar02, you might want to remove this :-)
```suggestion
        let document = Document::load(self.file)
            .with_context(|| format!("Failed to read PDF from: {:?}.", self.file))?;
```

2024-10-12 18:53 UTC, jeertmans commented on src/cli/annotations.rs
> +            "Successfully merged annotations from {} files to {:?}",
Missing a perdiod :-)
```suggestion
            "Successfully merged annotations from {} files to {:?}.",
```

2024-10-13 10:12 UTC, jeertmans commented on src/cli/annotations.rs
> +    file: &Path,
```suggestion
    file: PathBuf,
```
I think this is breaking the CI, is it an intentional change?

2024-10-15 14:36 UTC, Brijeshthummar02 commented
@jeertmans i'm not getting why this is breaking the CI

2024-10-15 15:21 UTC, jeertmans commented on src/cli/annotations.rs
> +
```suggestion
        let document = Document::load(&self.file)  
            .with_context(|| format!("Failed to read PDF from: {:?}.", self.file))?;  
```

This is the reason this was breaking (the removal of `&`).

2024-10-15 15:37 UTC, jeertmans commented
I'll fix formatting another day, thanks for your contribution @Brijeshthummar02  :-)

2024-10-15 15:37 UTC, merged

2024-10-15 15:38 UTC, Brijeshthummar02 commented
thankyou for the guidence.